### ISSUE TITLE
Error trying to deploy to iis on remote server, WINRM IIS DEPLOY TASK

### ISSUE THREAD

**Issue by Alcruz** [Microsoft/vsts-rm-extensions#97] opened 2016-09-09 21:05 UTC
![tfs](https://cloud.githubusercontent.com/assets/2265826/18402861/933aa8ee-76af-11e6-9a44-cb4c32398d76.PNG)

> 2016-09-09T20:41:52.3332647Z Executing the powershell script: Z:\TfsBuildAgents\VsoBuildAgent\tasks\IISWebAppDeploy\1.1.2\Main.ps1
> 2016-09-09T20:41:52.8800032Z Starting deployment of IIS Web Deploy Package : C:\SIPS\Sips.Web.zip
> 2016-09-09T20:41:53.1143197Z Performing deployment in parallel on all the machines.
> 2016-09-09T20:41:53.1143197Z Deployment started for machine: 172.16.0.125 with port 5985.
> 2016-09-09T20:42:54.5207789Z Deployment status for machine 172.16.0.125 : Microsoft.VisualStudio.Services.DevTestLabs.Definition.DeploymentResponse.Status
> 2016-09-09T20:42:54.5364002Z Deployment failed on machine 172.16.0.125 with following message : System.Exception: An object at the specified path C:\Users\E2586~1.SAN does not exist.
> 2016-09-09T20:42:54.5676428Z ##[error]Deployment on one or more machines failed.
> 2016-09-09T20:42:54.5676428Z ##[error]For more info please refer to http://aka.ms/iisextnreadme

**Comment by Alcruz** [comment] 2016-09-12 14:29
This error occurs when the username has a period.

**Comment by mvvsubbu** [comment] 2016-09-14 11:18
Thanks for reporting the issue, if you have fix you can float a PR we are accepting contributions.

**Comment by mvvsubbu** [comment] 2016-09-19 04:43
Can you set system.debug flag to true and send us the full logs

**Comment by mvvsubbu** [comment] 2016-10-12 05:13
The issue is fixed it will available in 1.2.4 release which should be out this week and hence I am closing this issue if it happens again feel free to re-open the issue

**Closed by mvvsubbu** 2016-10-12 05:13 UTC
Labels: bug
