### ISSUE TITLE
Access is denied. 

### ISSUE THREAD

**Issue by SDmorgan** [Microsoft/vsts-rm-extensions#176] opened 2017-01-20 07:34 UTC
OK. This is frustrating me. 

I can remote to the host with Using WinRM and the account that I'm using to deploy, however, when I add the same credentials, this is what I get... Note the account has admin rights and full rights on the folders it is publishing to.

VSTS is hosted by MS
Agent on remote host is the one that is bound to the release. 
The msbuild web deploy zip file get published using File Copy
Then it crashes. 

See below.

May be something obvious! Just can't see it. As mentioned, account being used has admin and full privileges to folder.

2017-01-20T07:17:44.1644601Z Performing deployment in parallel on all the machines.
 
2017-01-20T07:17:44.1644601Z 
 
2017-01-20T07:17:44.1644601Z 
 
2017-01-20T07:17:44.1644601Z Deployment started for machine: XXX-XXX-01 with port 5985.
 
2017-01-20T07:17:44.1644601Z 
 
2017-01-20T07:17:44.1644601Z 
 
2017-01-20T07:17:54.5632157Z Deployment status for machine XXX-XXX-01 : Failed
 
2017-01-20T07:17:54.5632157Z 
 
2017-01-20T07:17:54.5632157Z 
 
2017-01-20T07:17:54.5632157Z Deployment failed on machine XXX-XXX-01 with following message : System.Management.Automation.Remoting.PSRemotingTransportException: Connecting to remote server XXX-XXX-01 failed with the following error message : Access is denied. For more information, see the about_Remote_Troubleshooting Help topic.
 
2017-01-20T07:17:54.5632157Z    at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
 
2017-01-20T07:17:54.5632157Z    at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.EndOpen(IAsyncResult asyncResult)

**Comment by mvvsubbu** [comment] 2017-01-25 11:21
Can you help me with the following details.

1. What is the task you are using?
2. Can you share the logs of the release by setting system.debug variable to build or release with value as true.
3. Are you using hosted agent or private agent?
4. Is your target machine within corp net?

**Comment by mvvsubbu** [comment] 2017-01-30 16:08
Any update?

**Comment by mvvsubbu** [comment] 2017-02-07 11:40
Closing the issue as nothing is actionable. If you are still blocked you can open the issue share requested details.

**Closed by mvvsubbu** 2017-02-07 11:40 UTC

**Comment by hbopuri** [comment] 2017-10-25 19:08
Hi @mvvsubbu, I have same issue when setting up a build on VSTS to a VM on Azure.

> Microsoft.PowerShell.Commands.WriteErrorException: Deployment on one or more machines failed. System.Management.Automation.Remoting.PSRemotingTransportException: Connecting to remote server xxxxx.eastus.cloudapp.azure.com failed with the following error message : Access is denied. For more information, see the about_Remote_Troubleshooting Help topic.
posted same question over here: https://stackoverflow.com/questions/46919336/sql-project-deploy-to-sql-server-on-vm-through-visual-studio-team-services

I verified admin username and passwords are right. But still it says Access i denied

**Comment by cbonezzi** [comment] 2018-10-24 19:12
Hi there!
I am facing this exact issue with TFS 2017 Update 3 On-Premise. 
I am trying to use WinRM - IIS Web App Deployment. My configuration is as follows:
I have a build server (Running TFS)
I have a dev environment that hosts webserver (website) and sql database.
Webserver and TFS Build server are both on same Domain. 

This is the configuration of my release step
![image](https://user-images.githubusercontent.com/8673768/47455102-9b937a80-d796-11e8-8bb2-97a551131695.png)

Here is my log file with errors

Microsoft.PowerShell.Commands.WriteErrorException: Deployment on one or more machines failed. System.Management.Automation.Remoting.PSRemotingTransportException: Connecting to remote server UPEXCHANGE-DEV failed with the following error message : Access is denied. For more information, see the about_Remote_Troubleshooting Help topic.
--
  | PowerShell script completed with 1 errors.



2018-10-24T18:59:10.9605632Z ##[section]Starting: Manage IIS App: UPEnterpriseTest
2018-10-24T18:59:11.0074801Z ==============================================================================
2018-10-24T18:59:11.0074801Z Task         : WinRM - IIS Web App Management
2018-10-24T18:59:11.0074801Z Description  : Connect via WinRM, to create or update the Website and App Pool locally on IIS
2018-10-24T18:59:11.0074801Z Version      : 1.3.5
2018-10-24T18:59:11.0074801Z Author       : Microsoft Corporation
2018-10-24T18:59:11.0074801Z Help         : [More Information](http://aka.ms/IISMgmt)
2018-10-24T18:59:11.0074801Z ==============================================================================
2018-10-24T18:59:11.0699536Z Preparing task execution handler.
2018-10-24T18:59:11.7574773Z Executing the powershell script: D:\agent_tfs\_work\_tasks\IISWebAppMgmt_0f5cd14f-3c01-4d5c-8f7a-eb96c5738dcc\1.3.5\Main.ps1
2018-10-24T18:59:12.3043911Z Started creating website: UPEnterpriseTest
2018-10-24T18:59:12.3043911Z 
2018-10-24T18:59:12.3043911Z 
2018-10-24T18:59:12.5543941Z Performing deployment in parallel on all the machines.
2018-10-24T18:59:12.5543941Z 
2018-10-24T18:59:12.5543941Z 
2018-10-24T18:59:12.5700301Z Deployment started for machine: UPEXCHANGE-DEV with port 5985.
2018-10-24T18:59:12.5700301Z 
2018-10-24T18:59:12.5700301Z 
2018-10-24T18:59:23.5391402Z Deployment status for machine UPEXCHANGE-DEV : Failed
2018-10-24T18:59:23.5391402Z 
2018-10-24T18:59:23.5391402Z 
2018-10-24T18:59:23.5703909Z Deployment failed on machine UPEXCHANGE-DEV with following message : System.Management.Automation.Remoting.PSRemotingTransportException: Connecting to remote server UPEXCHANGE-DEV failed with the following error message : Access is denied. For more information, see the about_Remote_Troubleshooting Help topic.
2018-10-24T18:59:23.5703909Z    at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
2018-10-24T18:59:23.5703909Z    at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.EndOpen(IAsyncResult asyncResult)
2018-10-24T18:59:23.5703909Z    at System.Management.Automation.RemoteRunspace.Open()
2018-10-24T18:59:23.5703909Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.GetOpenedRunspace()
2018-10-24T18:59:23.5703909Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.EstablishRemoteSession()
2018-10-24T18:59:23.5703909Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.RetryExecutor.Execute(Action action)
2018-10-24T18:59:23.5703909Z    at System.Threading.Tasks.Task.Execute()
2018-10-24T18:59:23.5703909Z --- End of stack trace from previous location where exception was thrown ---
2018-10-24T18:59:23.5703909Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-10-24T18:59:23.5703909Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-10-24T18:59:23.5703909Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.<Initialize>d__29.MoveNext()
2018-10-24T18:59:23.5703909Z --- End of stack trace from previous location where exception was thrown ---
2018-10-24T18:59:23.5703909Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-10-24T18:59:23.5703909Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-10-24T18:59:23.5703909Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.<Initialize>d__23.MoveNext()
2018-10-24T18:59:23.5703909Z --- End of stack trace from previous location where exception was thrown ---
2018-10-24T18:59:23.5703909Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-10-24T18:59:23.5703909Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-10-24T18:59:23.5703909Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.RemoteDeploymentHelper.<Initialize>d__0.MoveNext()
2018-10-24T18:59:23.5703909Z --- End of stack trace from previous location where exception was thrown ---
2018-10-24T18:59:23.5703909Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-10-24T18:59:23.5703909Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-10-24T18:59:23.5703909Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.DeploymentClient.<RunAsync>d__24.MoveNext()
2018-10-24T18:59:23.5703909Z 
2018-10-24T18:59:23.5703909Z 
2018-10-24T18:59:23.6485051Z 
2018-10-24T18:59:23.6485051Z 
2018-10-24T18:59:23.6797555Z ##[error]Microsoft.PowerShell.Commands.WriteErrorException: Deployment on one or more machines failed. System.Management.Automation.Remoting.PSRemotingTransportException: Connecting to remote server UPEXCHANGE-DEV failed with the following error message : Access is denied. For more information, see the about_Remote_Troubleshooting Help topic.
2018-10-24T18:59:23.6797555Z    at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
2018-10-24T18:59:23.6797555Z    at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.EndOpen(IAsyncResult asyncResult)
2018-10-24T18:59:23.6797555Z    at System.Management.Automation.RemoteRunspace.Open()
2018-10-24T18:59:23.6797555Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.GetOpenedRunspace()
2018-10-24T18:59:23.6797555Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.EstablishRemoteSession()
2018-10-24T18:59:23.6797555Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.RetryExecutor.Execute(Action action)
2018-10-24T18:59:23.6797555Z    at System.Threading.Tasks.Task.Execute()
2018-10-24T18:59:23.6797555Z --- End of stack trace from previous location where exception was thrown ---
2018-10-24T18:59:23.6797555Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-10-24T18:59:23.6797555Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-10-24T18:59:23.6797555Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.<Initialize>d__29.MoveNext()
2018-10-24T18:59:23.6797555Z --- End of stack trace from previous location where exception was thrown ---
2018-10-24T18:59:23.6797555Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-10-24T18:59:23.6797555Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-10-24T18:59:23.6797555Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.<Initialize>d__23.MoveNext()
2018-10-24T18:59:23.6797555Z --- End of stack trace from previous location where exception was thrown ---
2018-10-24T18:59:23.6797555Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-10-24T18:59:23.6797555Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-10-24T18:59:23.6797555Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.RemoteDeploymentHelper.<Initialize>d__0.MoveNext()
2018-10-24T18:59:23.6797555Z --- End of stack trace from previous location where exception was thrown ---
2018-10-24T18:59:23.6797555Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-10-24T18:59:23.6797555Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-10-24T18:59:23.6797555Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.DeploymentClient.<RunAsync>d__24.MoveNext()
2018-10-24T18:59:23.6797555Z For more info please refer to http://aka.ms/iisextnreadme
2018-10-24T18:59:23.7110148Z ##[error]PowerShell script completed with 1 errors.
2018-10-24T18:59:23.7266334Z ##[section]Finishing: Manage IIS App: UPEnterpriseTest

Any help or pointers will be greatly appreciated

**Comment by Ajay-MS** [comment] 2018-10-26 06:12
@cbonezzi 

Please check that user you are trying to log in on remote machine has proper permission. 

You can verify connection using `Enter-PSSession` cmdlet. 

**Sample Script to verify the connection** 
```
$soptions = New-PSSessionOption -SkipCACheck
$cred = Get-Credential
$computername = "<Computer Name>"
$computerport = 5985
Enter-PSSession -ComputerName $computername -Port $computerport -Credential $cred -SessionOption $soptions      # -UserSSL 
```

Also refer [access denied thread](https://stackoverflow.com/questions/22680211/access-denied-on-remote-winrm) on SO.

**Comment by cbonezzi** [comment] 2018-10-26 13:50
@Ajay-MS 
this step helped me find the permission of such user. I had my IT manager create a user in the domain that has full rights. After this change, I was able to get rid of the access denied.

Thanks.

**Comment by Ajay-MS** [comment] 2018-10-29 05:34
@cbonezzi 

Thanks for the confirmation. Happy to know that you are unblocked on this issue.

**Comment by rexren78** [comment] 2019-08-27 04:48
@SDmorgan ，have you found any idea to fix this problem? I meet the issue, too.

**Comment by rexren78** [comment] 2019-08-27 04:50
The problem is not the user cannot execute the command but the user cannot execute the command on the hosted Agent.
