### ISSUE TITLE
Tests fail on Unix (Linux and Mac OS X)

### ISSUE THREAD

**Issue by pdesgarets** [Microsoft/vsts-rm-extensions#412] opened 2018-04-09 11:19 UTC
Hi,
Tests fail UNIX systems, see https://travis-ci.org/pdesgarets/vsts-rm-extensions/builds/364061762 
Thanks

**Comment by omeshp** [comment] 2018-04-16 13:42
#417

**Comment by omeshp** [comment] 2018-04-17 08:32
@pdesgarets The issue is fixed now.

**Closed by omeshp** 2018-04-17 08:32 UTC

**Comment by pdesgarets** [comment] 2018-04-17 08:36
Thanks ! Do you know when it will be released on VSTS public website ? It may solve https://developercommunity.visualstudio.com/content/problem/230303/artifacts-selection-for-release-works-only-on-wind.html .

**Comment by omeshp** [comment] 2018-04-17 08:46
@pdesgarets yes to fix that issue we need some server side change also, which should be deployed in 3-4 days.

**Comment by pdesgarets** [comment] 2018-04-17 08:50
Great, thanks
